/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameFactory } from "./GameFactory";
export type { TwoThirdsAverageGame } from "./TwoThirdsAverageGame";
