/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GameFactory__factory } from "./GameFactory__factory";
export { TwoThirdsAverageGame__factory } from "./TwoThirdsAverageGame__factory";
